# rails_developer.yml
---
- name: Rails Developer VM
  hosts: all
  roles:
    - core
    - gemrc
    - nodejs
    - { role: set_locale, sudo: yes }
    - { role: jfredee.galaxy-rbenv-ruby, ruby_version: 2.1.2, rbenv_user: vagrant }
    - { role: postgresql, sudo: yes }
    - { role: mailcatcher, sudo: yes }
    - { role: rails_setup, sudo: yes }
