# ordered list of recipes to run
recipes:
- custom_helpers
- git_init
- base
- webapp
- testsuite
- rails_javascript
- continuous_integration
- continuous_testing
- email_init
- hosting
- integrations
- vagrant

# set of configurable preferences for the template to run
# change the remote_branch to a feature branch when testing
# changes
prefs:
  :remote_host: https://raw.github.com/thegarage/thegarage-template
  :remote_branch: master
  :github_organization: thegarage
  :github_deployer_account: admin@thegarage.us

# list of gems to install
gems:
- bundler
