guard :shellexec, command: './bin/restart' do
  watch('.env')
  watch('.ruby-version')
  watch('Gemfile.lock')
  watch('config/application.rb')
  watch('config/environment.rb')
  watch(%r{^config/environments/.*\.rb$})
  watch(%r{^config/initializers/.*\.rb$})
end
