---
- name: core | core essentials
  apt: name={{ item }} state=latest update_cache=yes
  sudo: yes
  with_items:
    - build-essential
    - cmake
    - vim
    - git
    - curl
    - libsqlite3-dev
    - libfontconfig1
    - libffi-dev
